x-common-env: &common-env
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}

x-certs-volume: &certs-volume ${CERTS}:/certs:ro

x-logging-labels: &logging-labels
  logging: promtail
  jobname: container_logs

x-lockdown: &lockdown
  read_only: true
  security_opt:
    - "no-new-privileges=true"

services:
  tdarr:
    image: "ghcr.io/haveagitgat/tdarr:latest"
    container_name: tdarr
    profiles: ['not-arr']
    environment:
      <<: *common-env
      serverUrl: ${TDARR_URL}
      webUIPort: 8265
      internalNode: true
      inContainer: true
      ffmpegVersion: 7
      nodeName: "TdarrServer"
      auth: false
      openBrowser: true
      maxLogSizeMB: 5
      cronPluginUpdate:
    volumes:
      - "tdarr.server:/app/server"
      - "tdarr.configs:/app/configs"
      - ${DOCKER_CONFIG}/scripts:/scripts
      - ${FILESHARE}:/data
    tmpfs:
      - "/tmp:size=8g"
      - "/app/logs:size=32m"
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    networks:
      - "defaultNet"
    restart: unless-stopped
    group_add:
      - '105'
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

  jellyfin:
    image: "jellyfin/jellyfin:10.11"
    container_name: jellyfin
    hostname: jellyfin
    profiles: ['not-arr']
    user: ${PUID}:${PGID}
    environment:
      <<: *common-env
    volumes:
      # Config
      - "jellyfin.conf:/config"
      # Media
      - ${FILESHARE}:/videos
      # Metadata
      - /media/metadata/jellyfin:/config/metadata
    tmpfs:
      - "/cache:uid=${PUID},gid=${PGID}"
      - "/config/log:uid=${PUID},gid=${PGID},size=32m"
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    networks:
      - "defaultNet"
    restart: "unless-stopped"
    group_add:
      - '105'
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

## Arr ##
  gluetun:
    image: "qmcgaw/gluetun:v3"
    container_name: gluetun
    profiles: ['arr']
    environment:
      <<: *common-env
      # Mullvad-WG
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: 10.73.70.3/32
      WIREGUARD_ENDPOINT_PORT: 52001
      SERVER_COUNTRIES: Sweden

      # Options
      SHADOWSOCKS: off
      FIREWALL: on
      FIREWALL_OUTBOUND_SUBNETS: 10.40.40.0/24,10.255.255.0/24
      DOT: on
      UPDATER_PERIOD: 48h
      OWNED_ONLY: on
    ports:
      - 8000:8000/tcp # HTTP Control
      - 6555:6555/tcp # qBit WebUI
      - ${RADARR_SERVER_SSLPORT}:${RADARR_SERVER_SSLPORT}/tcp
      - ${SONARR_SERVER_SSLPORT}:${SONARR_SERVER_SSLPORT}/tcp
      - ${PROWLARR_SERVER_SSLPORT}:${PROWLARR_SERVER_SSLPORT}/tcp
    volumes:
      - "gluetun.conf:/gluetun"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - "arrNet"
    restart: "unless-stopped"

  qbit:
    image: "11notes/qbittorrent:5.1.4"
    container_name: qbit
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
    volumes:
      - "qbittorrent.etc:/qbittorrent/etc"
      - "qbittorrent.var:/qbittorrent/var"
      # To conform with arrs directory mappings without using path mappings
      - ${FILESHARE}/Downloads:/data/Downloads
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  sonarr:
    image: "11notes/sonarr:4.0.17"
    container_name: sonarr
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
      SONARR__APP__THEME: "light"
      SONARR__LOG__LEVEL: "${SONARR_LOG_LEVEL}"
      SONARR__LOG__DBENABLED: "${SONARR_LOG_DBENABLED}"
      SONARR__LOG__ANALYTICSENABLED: "false"
      SONARR__POSTGRES__HOST: "${SONARR_POSTGRES_HOST}"
      SONARR__POSTGRES__PORT: "${SONARR_POSTGRES_PORT}"
      SONARR__POSTGRES__USER: "${SONARR_POSTGRES_USER}"
      SONARR__POSTGRES__PASSWORD: "${SONARR_POSTGRES_PASSWORD}"
      SONARR__POSTGRES__MAINDB: "${SONARR_POSTGRES_MAINDB}"
      SONARR__SERVER__ENABLESSL: "true"
      SONARR__SERVER__SSLPORT: "${SONARR_SERVER_SSLPORT}"
      SONARR__SERVER__SSLCERTPATH: "/certs/docker.pfx"
      SONARR__SERVER__SSLCERTPASSWORD: "${CERT_PASSWORD}"
      SONARR__SERVER__PORT: "8989"
    volumes:
      - "sonarr.etc:/sonarr/etc"
      - ${ARR_BACKUPS}/sonarr:/config/backups
      - ${FILESHARE}:/data
      - *certs-volume
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
      - "/logs:uid=${PUID},gid=${PGID}"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  radarr:
    image: "11notes/radarr:6"
    container_name: "radarr"
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
      RADARR__APP__THEME: "light"
      RADARR__LOG__LEVEL: "${RADARR_LOG_LEVEL}"
      RADARR__LOG__DBENABLED: "${RADARR_LOG_DBENABLED}"
      RADARR__LOG__ANALYTICSENABLED: "false"
      RADARR__POSTGRES__HOST: "${RADARR_POSTGRES_HOST}"
      RADARR__POSTGRES__PORT: "${RADARR_POSTGRES_PORT}"
      RADARR__POSTGRES__USER: "${RADARR_POSTGRES_USER}"
      RADARR__POSTGRES__PASSWORD: "${RADARR_POSTGRES_PASSWORD}"
      RADARR__POSTGRES__MAINDB: "${RADARR_POSTGRES_MAINDB}"
      RADARR__SERVER__ENABLESSL: "true"
      RADARR__SERVER__SSLPORT: "${RADARR_SERVER_SSLPORT}"
      RADARR__SERVER__SSLCERTPATH: "/certs/docker.pfx"
      RADARR__SERVER__SSLCERTPASSWORD: "${CERT_PASSWORD}"
      RADARR__SERVER__PORT: "7878"
    volumes:
      - "radarr.etc:/radarr/etc"
      - ${ARR_BACKUPS}/radarr:/config/backups
      - ${FILESHARE}:/data
      - *certs-volume
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
      - "/logs:uid=${PUID},gid=${PGID}"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  prowlarr:
    image: "11notes/prowlarr:2.3.0"
    container_name: prowlarr
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
      PROWLARR__APP__THEME: "light"
      PROWLARR__LOG__LEVEL: "${PROWLARR_LOG_LEVEL}"
      PROWLARR__LOG__DBENABLED: "${PROWLARR_LOG_DBENABLED}"
      PROWLARR__LOG__ANALYTICSENABLED: "false"
      PROWLARR__POSTGRES__HOST: "${PROWLARR_POSTGRES_HOST}"
      PROWLARR__POSTGRES__PORT: "${PROWLARR_POSTGRES_PORT}"
      PROWLARR__POSTGRES__USER: "${PROWLARR_POSTGRES_USER}"
      PROWLARR__POSTGRES__PASSWORD: "${PROWLARR_POSTGRES_PASSWORD}"
      PROWLARR__POSTGRES__MAINDB: "${PROWLARR_POSTGRES_MAINDB}"
      PROWLARR__SERVER__ENABLESSL: "true"
      PROWLARR__SERVER__SSLPORT: "${PROWLARR_SERVER_SSLPORT}"
      PROWLARR__SERVER__SSLCERTPATH: "/certs/docker.pfx"
      PROWLARR__SERVER__SSLCERTPASSWORD: "${CERT_PASSWORD}"
      PROWLARR__SERVER__PORT: "9696"
    volumes:
      - "prowlarr.etc:/prowlarr/etc"
      - ${ARR_BACKUPS}/prowlarr:/config/backups
      - *certs-volume
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
      - "/logs:uid=${PUID},gid=${PGID}"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

# -----END------

  immich-machine-learning:
    container_name: immich_machine_learning
    profiles: ['immich']
    image: ghcr.io/immich-app/immich-machine-learning:v2.7.3-openvino
    volumes:
      - "immich_model-cache:/cache"
    # External access
    ports:
      - 3003:3003
    extends:
      file: ${DOCKER_CONFIG}/immich/hwaccel.ml.yml
      service: openvino # [armnn, cuda, openvino, openvino-wsl]
    group_add:
      - '105'
    networks:
      - immichNet
    restart: always
    healthcheck:
      disable: false

volumes:
  tdarr.server:
  tdarr.configs:
  jellyfin.conf:
  gluetun.conf:
  qbittorrent.etc:
  qbittorrent.var:
  sonarr.etc:
  radarr.etc:
  prowlarr.etc:
  immich_model-cache:

networks:
  defaultNet:
    name: defaultNet
    driver: bridge
  arrNet:
    name: arrNet
    driver: bridge
  immichNet:
    name: immichNet
    driver: bridge
