x-common-env: &common-env
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}

x-certs-volume: &certs-volume ${CERTS}:/certs:ro

x-logging-labels: &logging-labels
  logging: promtail
  jobname: container_logs

x-lockdown: &lockdown
  read_only: true
  security_opt:
    - "no-new-privileges=true"

services:
  tdarr:
    image: "ghcr.io/haveagitgat/tdarr:latest"
    container_name: tdarr
    profiles: ['not-arr']
    environment:
      <<: *common-env
      serverUrl: ${TDARR_URL}
      webUIPort: 8265
      internalNode: true
      inContainer: true
      ffmpegVersion: 7
      nodeName: "TdarrServer"
      auth: false
      openBrowser: true
      maxLogSizeMB: 5
      cronPluginUpdate:
    volumes:
      - "tdarr.server:/app/server"
      - "tdarr.configs:/app/configs"
      - ${DOCKER_CONFIG}/scripts:/scripts
      - ${FILESHARE}:/data
    tmpfs:
      - "/tmp:size=8g"
      - "/app/logs:size=32m"
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    networks:
      - "defaultNet"
    restart: unless-stopped
    group_add:
      - '105'
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

  jellyfin:
    image: "jellyfin/jellyfin:10.11"
    container_name: jellyfin
    hostname: jellyfin
    profiles: ['not-arr']
    user: ${PUID}:${PGID}
    environment:
      <<: *common-env
    volumes:
      # Config
      - "jellyfin.conf:/config"
      # Media
      - ${FILESHARE}:/videos
      # Metadata
      - /media/metadata/jellyfin:/config/metadata
    tmpfs:
      - "/cache:uid=${PUID},gid=${PGID}"
      - "/config/log:uid=${PUID},gid=${PGID},size=32m"
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    networks:
      - "defaultNet"
    restart: "unless-stopped"
    group_add:
      - '105'
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

## Arr ##
  gluetun:
    image: "qmcgaw/gluetun:v3"
    container_name: gluetun
    profiles: ['arr']
    environment:
      <<: *common-env
      # Mullvad-WG
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: 10.73.70.3/32
      WIREGUARD_ENDPOINT_PORT: 52001
      SERVER_COUNTRIES: Sweden

      # Options
      SHADOWSOCKS: off
      FIREWALL: on
      FIREWALL_OUTBOUND_SUBNETS: 10.40.40.0/24,10.255.255.0/24
      DOT: on
      UPDATER_PERIOD: 48h
      OWNED_ONLY: on
    ports:
      - 8000:8000/tcp # Homepage IP parse
      - 6555:6555/tcp # qBit WebUI
      - 6868:6868/tcp # Profilarr
      - 9898:9898/tcp # Radarr TLS
      - 9897:9897/tcp # Sonarr TLS
      - 6969:6969/tcp # Prowlarr TLS
      - 9705:9705/tcp # Huntarr
    volumes:
      - "gluetun.conf:/gluetun"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - "arrNet"
    restart: "unless-stopped"

  qbit:
    image: "11notes/qbittorrent:5.1.4"
    container_name: qbit
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
    volumes:
      - "qbittorrent.etc:/qbittorrent/etc"
      - "qbittorrent.var:/qbittorrent/var"
      # To conform with arrs directory mappings without using path mappings
      - ${FILESHARE}/Downloads:/data/Downloads
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  sonarr:
    image: "11notes/sonarr:4.0.17"
    container_name: sonarr
    read_only: true
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
    volumes:
      - "sonarr.etc:/sonarr/etc"
      - ${ARR_BACKUPS}/sonarr:/config/backups
      - ${FILESHARE}:/data
      - *certs-volume
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
      - "/logs:uid=${PUID},gid=${PGID}"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  radarr:
    image: "11notes/radarr:6"
    container_name: radarr
    read_only: true
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
    volumes:
      - "radarr.etc:/radarr/etc"
      - ${ARR_BACKUPS}/radarr:/config/backups
      - ${FILESHARE}:/data
      - *certs-volume
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
      - "/logs:uid=${PUID},gid=${PGID}"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

  prowlarr:
    image: "11notes/prowlarr:2.3.0"
    container_name: prowlarr
    read_only: true
    profiles: ['arr']
    user: ${PUID}:${PGID}
    <<: *lockdown
    environment:
      TZ: ${TZ}
    volumes:
      - "prowlarr.etc:/prowlarr/etc"
      - ${ARR_BACKUPS}/prowlarr:/config/backups
      - *certs-volume
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
      - "/logs:uid=${PUID},gid=${PGID}"
    network_mode: "service:gluetun"
    restart: "unless-stopped"

# -----END------

  immich-machine-learning:
    container_name: immich_machine_learning
    profiles: ['immich']
    image: ghcr.io/immich-app/immich-machine-learning:v2.6.1-openvino
    volumes:
      - "immich_model-cache:/cache"
    env_file:
      - .env.immich
    # External access
    ports:
      - 3003:3003
    extends:
      file: ${DOCKER_CONFIG}/immich/hwaccel.ml.yml
      service: openvino # [armnn, cuda, openvino, openvino-wsl]
    group_add:
      - '105'
    networks:
      - immichNet
    restart: always
    healthcheck:
      disable: false

volumes:
  tdarr.server:
  tdarr.configs:
  jellyfin.conf:
  gluetun.conf:
  qbittorrent.etc:
  qbittorrent.var:
  sonarr.etc:
  radarr.etc:
  prowlarr.etc:
  immich_model-cache:

networks:
  defaultNet:
    name: defaultNet
    driver: bridge
  arrNet:
    name: arrNet
    driver: bridge
  immichNet:
    name: immichNet
    driver: bridge
